#application-local.yml (절대 깃허브에 올리면 안 됨)
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/mydiary
    username: mydiary_user
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

jwt:
  secret: "myDiarySecretKeyForJwtTokenGeneration1234567890!!"
  expiration: 86400000